name: Rspec

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6.5
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - name: Build
        run: |
          sudo apt-get install libsqlite3-dev
          gem install bundler:2.1.4
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rspec
